name: Deploy Node.js app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SECRET_SERVER_IP }}
          username: root
          password: ${{ secrets.SECRET_SERVER_PASSWORD }}
          port: 22
          script: |
            cd /var/www/cohortgenie-BE
            git pull
            npm i
            pm2 restart cohortgenie-BE
